version: '3'

networks:
  laravel:


services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8088:80"
    volumes:
      - ../under-the-woods:/var/www/html:delegated
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - laravel

  mysql:
    image: mariadb:11.1.1-rc-jammy
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3307"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_PASSWORD: secret
      MYSQL_USER: homestead
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql

    networks:
      - laravel

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ../under-the-woods:/var/www/html:delegated
    ports:
      - "9000:9000"
    networks:
      - laravel

  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - ../under-the-woods:/var/www/html:delegated
    working_dir: /var/www/html
    networks:
      - laravel

  npm:
    image: node:18-alpine
    container_name: npm
    volumes:
      - ../under-the-woods:/var/www/html:delegated
    working_dir: /var/www/html
    entrypoint: [ 'npm' ]
    networks:
      - laravel

  artisan:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: artisan
    volumes:
      - ../under-the-woods:/var/www/html:delegated
    depends_on:
      - mysql
    working_dir: /var/www/html
    entrypoint: [ '/var/www/html/artisan' ]
    networks:
      - laravel
